---
title: "Data CLeaning Course Project"
author: "Duncan Turnbull"
date: "20 December 2014"
output: html_document
---

## Overview
The project requirement is to take raw data and turn it into tidy data. The data is an online zip file and is part of the "Human Activity Recognition Using Smartphones Data Set". It has come from a group of 30 volunteers aged between 19 & 48. The data is the accelerations recorded as they move using a smartphone accelerometer and gyroscope.

## Project Requirements
You should create one R script called run_analysis.R that does the following. 

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement. 
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names. 
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

### Part 1
* Download data and unzip
* load test and training sets
    + load row and column labels 
        + clean column and row labels
        + apply labels
    + add variable to reflect data type from file
    + add variable to reflect whether test or train data
* Merge data 

### Part 2: select std deviation and mean data only
* Once all data is in one table discard non necessary columns or 
* could try reading in only required columns or remove straight away
    + would require an early logical vector of which columns are required.
    + whats the best way to do this?

### Part 3: Name the activities appropriately
* Need to define all included activities - walk, run, upstairs etc, these are the rows

### Part 4
* Label variable names (columns)

### Part 5 
* create a second, independent tidy data set with the average of each variable for each activity and each subject.

# Overview
There are a range of files that need to be merged. The observations are raw data, there is a user file linking the user ids to the rows

The file names reflect the data types and the directories they are in also split between the test and train group

## Part 1
0. Setup parameters
    * Setup directories to access data folder
    * Get specific files mapping to directories
1. Read labels and clean them
    * Move to "UCI HAR Dataset" dir
    * read the files "activity_labels.txt" ,"features.txt"
    * Read the label files ( and clean them if needed )
    * Read the files into data tables and add vars for test/train bod/gyro/tot
    * label the files
    * add 
2.  Read files

```{r eval=FALSE}
activitylabels <- read.table(file = "features.txt")
# Get the required activity columns
actcols <- grep("(mean|std)\\(\\)",activitylabels$V2)
activitylabels[,2] <- gsub(activitylabels[,2],pattern = "[-(),]", replacement = ""  )

ytrain <- read.table(file = "./train//y_train.txt")
ytest <- read.table(file = "./test/y_test.txt")
activity <- rbind(ytest,ytrain)
actlabels  <- read.table(file = "./activity_labels.txt")
activitynames <- as.character(actlabels$V2)[activity$V1]

testsubject <- read.table(file = "./test//subject_test.txt")
trainsubject <- read.table(file = ".//train//subject_train.txt")
subject <- rbind(testsubject, trainsubject)

xtest <- read.table(file = "./test/X_test.txt")
features <- read.table(file = "./features.txt")
colnames(xtest) <- features$V2
xtest$type="test"
xtrain <- read.table(file = "./Documents/R Programming/R - Data Cleaning/data/UCI HAR Dataset/train//X_train.txt")
colnames(xtrain) <- features$V2
xtrain$type="train"
data <- rbind(xtest,xtrain)
names <- names(data)
data <- cbind(subject,activity,activitynames,data)
colnames(data) <-c("Subject","Activity","ActivityName", as.character(names))

# Use previously selected active columns to remove anything but mean or std
data2 <-data[,c(1:4,actcols+4)]
```